apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reejig
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aadi308/helm-argocd.git
    chart: reejig
    helm:
      valueFiles:
      - values.yaml
      releaseName: reejig
  destination:
    server: "https://kubernetes.default.svc"
    namespace: reejig-argo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
