apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reejiig-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aadi308/helm-argocd.git
    path: helm-argo
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
